[package]
name = "wahgex-cli"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
wahgex = { path = "../core", version = "0.1" }
wasmparser = { workspace = true }
wasmprinter = { workspace = true }
